version: '3.3'
services:

  # Prometheus uses the image resulting form the build
  # of `./prometheus` which simply packs some configuration
  # into the form of an image.
  #
  # It could instead, use volume-mounts.
  prometheus:
    build: './prometheus'
    container_name: 'prometheus'
    ports:
      - '9090:9090'

  # The grafana container uses the image resulting from the build
  # of `./grafana` which simply packs some configuration into the
  # form of an image.
  #
  # This could instead be a volume-mounted container.
  grafana:
    build: './grafana'
    container_name: 'grafana'
    ports:
      - '3000:3000'

  # node_exporter:
  #   image: 'quay.io/prometheus/node-exporter'
  #   container_name: 'node_exporter'

  snmp_exporter:
    build: './snmp-exporter'
    container_name: 'snmp_exporter'
    ports:
      - '9116:9116'
    # volumes:
    #   - ./snmp/snmp.yml:/etc/snmp_exporter/snmp.yml