global:
  scrape_interval: '5s'
  evaluation_interval: '5s'

scrape_configs:

  # `node` takes care of scraping node_exporter instances
  # that gives us all sorts of information about the host
  # in which the exporter runs.
  # - job_name: 'node'
  #   static_configs:
  #     - targets:
  #       - 'node_exporter:9100'
  #       labels:
  #         instance: 'instance-1'

  - job_name: 'snmp'
    static_configs:
        - targets:
          - '10.103.0.165' # Target SNMP device.
    metrics_path: /snmp
    params:
      module: [bigip]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'snmp_exporter:9116'  # Docker IP with SNMP exporter.
